"""add_competitor_social_links

Revision ID: db3a7c3ea048
Revises: e72092cedb6f
Create Date: 2026-03-22 22:54:27.164864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db3a7c3ea048'
down_revision: Union[str, None] = 'e72092cedb6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitors', sa.Column('instagram_url', sa.String(length=500), nullable=True))
    op.add_column('competitors', sa.Column('facebook_url', sa.String(length=500), nullable=True))
    op.add_column('competitors', sa.Column('twitter_url', sa.String(length=500), nullable=True))
    op.add_column('competitors', sa.Column('linkedin_url', sa.String(length=500), nullable=True))
    op.add_column('competitors', sa.Column('tiktok_url', sa.String(length=500), nullable=True))
    op.add_column('competitors', sa.Column('youtube_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitors', 'youtube_url')
    op.drop_column('competitors', 'tiktok_url')
    op.drop_column('competitors', 'linkedin_url')
    op.drop_column('competitors', 'twitter_url')
    op.drop_column('competitors', 'facebook_url')
    op.drop_column('competitors', 'instagram_url')
    # ### end Alembic commands ###
